### ISSUE TITLE
Copy+Paste

### ISSUE THREAD

**Issue by imsnif** [imsnif/terminal-grid#10]
Currently, paste works with ctrl-shit-v... I couldn't get copy to work.
I think getting copy+paste to work with ctrl-shift-c and ctrl-shift-v - following most terminal emulators will be a good convention.
@qballer - want to check it out?

**Comment by qballer** [comment]
Yes. Why the the shift though ?

**Comment by imsnif** [comment]
ctrl-shift-c and ctrl-shift-v as copy/paste are a terminal convention. This is mostly because ctrl-c is very much taken. :)

**Comment by imsnif** [comment]
Turns out copy in xterm is shift+insert... which is not ideal.
Implemented ctrl+shift+c to copy.
