### ISSUE TITLE
What's in a name? 

### ISSUE THREAD

**Issue by qballer** [imsnif/terminal-grid#11]
- [x] Select a new name. 
- [ ] update readme.md

**Comment by qballer** [comment]
@imsnif decide on a name. My offer is ninja-term.

**Comment by imsnif** [comment]
How about knife? (or knife.js, knife.io, knife-term, etc.)
I'm thinking of this: http://www.foundrycoffee.com/i-should-talk-now-about-phaedrus-knife/

**Comment by qballer** [comment]
Amoeba ? (because it splits ... )

**Comment by imsnif** [comment]
Decided on AmoebaTerm - woohoo!
