### ISSUE TITLE
Formalize and fix shortcuts

### ISSUE THREAD

**Issue by imsnif** [imsnif/terminal-grid#16]
This is mostly a decision that needs to be made. How do shortcuts work? What are the default toggles? What would be most intuitive, etc.

**Comment by qballer** [comment]
Shortcuts come with flavors, our basics should be for 1. Mouse people 2. keyboard people. 
Besides that, let them share shortcuts configuration and what not.

**Comment by imsnif** [comment]
While I don't mind supporting basic mouse actions (move/resize windows) the main focus of this app is that it's keyboard controls. I want the keyboard shortcuts to be as intuitive and easy as possible though.

**Comment by imsnif** [comment]
Closing this issue as electron doesn't seem to give a lot of leeway regarding shortcuts. So I'm staying with what we have right now and at some point we'll make them configurable (as much as electron will allow).
