### ISSUE TITLE
TMUX mode

### ISSUE THREAD

**Issue by imsnif** [imsnif/terminal-grid#2]
Create a tmux mode that:
- [x] Creates a full work-space pane on app ready.
- [x] Allow splitting panes vertically and horizontally into 2 different panes.
- [x] Allows switching focus directionally between panes (https://github.com/imsnif/terminal-grid/issues/1)
- [x] Allows resizing panes over one another. (https://github.com/imsnif/terminal-grid/issues/14)
- [x] Allows closing panes and having other panes take up their space.
- [x] Allow temporary full work-space of pane toggle.
- [x] Allow minimizing all panes.
- [x] Allow switching between window contents (i.e. moving the terminal in one pane into another).

**Comment by qballer** [comment]
@imsnif changed this to checkbox, so we can track progress.

**Comment by imsnif** [comment]
I can't believe I'm writing this, but... implemented.
