### ISSUE TITLE
package the app

### ISSUE THREAD

**Issue by qballer** [imsnif/terminal-grid#24]
Be able to install the app in non dev mode with no dependencies. Just download and run.

**Comment by imsnif** [comment]
Added tray icon that allows you to quit the app for this purpose.
In the first release, we must not forget to credit this guy: http://www.flaticon.com/free-icon/organism_213244#term=biology%20organisms&page=1&position=1

**Comment by imsnif** [comment]
Done, minus a few glitches. Results can be seen in Releases.
Not placing this as part of package.json yet because this still needs to be extensively tested on various platforms.
