### ISSUE TITLE
Visual indication for focused Pane

### ISSUE THREAD

**Issue by imsnif** [imsnif/terminal-grid#4]
Change border color or some such.

**Comment by imsnif** [comment]
@qballer - I have a buggy version of this working... do you want to do this, or shall I fix and tidy mine?

**Comment by qballer** [comment]
If it works, fix yours for now. I need to fix the mismatch electron versions in my environment first.

**Comment by imsnif** [comment]
https://github.com/imsnif/electron-terminal-window/issues/1

**Comment by imsnif** [comment]
Implemented. It's kind of hacky but will work well for dev purposes.
Might want to think of a way to implement this better, solve some bugs in it and make it look more appealing.
